---
abstract: 'my tiny bot'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::Compile: '0'
  Test::Kwalitee: '0'
  Test::Mojo: '0'
  Test::More: '0'
  Test::NoTabs: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.021, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pika
requires:
  AnyEvent: '0'
  AnyEvent::IRC::Client: '0'
  Moose: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::App::Cmd: '0'
  MooseX::App::Cmd::Command: '0'
  MooseX::Role::Pluggable: '0'
  MooseX::Role::Pluggable::Plugin: '0'
  MooseX::SimpleConfig: '0'
  Quick::Perl: '0'
  namespace::autoclean: '0'
resources:
  repository: git://github.com/battlemidget/pika
version: 0.0.3
