---
abstract: 'my tiny bot'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  DBD::SQLite: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::Compile: '0'
  Test::Kwalitee: '0'
  Test::Mojo: '0'
  Test::More: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.021, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pika
requires:
  AnyEvent: '0'
  AnyEvent::IRC::Client: '0'
  Config::Any: '0'
  DBI: '0'
  IRC::Utils: '0'
  Module::Runtime: '0'
  Moose: '0'
  Moose::Util: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::App: '0'
  MooseX::App::Command: '0'
  Net::Launchpad::Client: '0'
  Net::Launchpad::Model: '0'
  Net::LeanKit: '0'
  Quick::Perl: '0'
  SQL::Abstract::More: '0'
  namespace::autoclean: '0'
  perl: '5.008'
resources:
  homepage: https://github.com/battlemidget/pika
  repository: https://github.com/battlemidget/pika.git
version: '1.001'
x_authority: cpan:ADAMJS
